version: '3.8'

services:
  instagram-cropper:
    build: .
    ports:
      - "8088:8088"
    environment:
      - HOST=0.0.0.0
      - PORT=8088
      - WORKERS=4
      - LOG_LEVEL=info
    volumes:
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - instagram-cropper
    restart: unless-stopped
